<?php
$pageTitle = 'How I Built This Site Using AI';
$isCaseStudy = false;
?>
<!DOCTYPE html>
<html lang="en">
<?php include __DIR__ . '/../includes/header.php'; ?>
<style>
.about-content p {
    font-size: 1rem !important;
    margin-bottom: var(--space-md) !important;
}
</style>
<body>
    <?php include __DIR__ . '/../includes/navigation.php'; ?>

    <main class="container">
        <section class="content-section">
            <div class="about-content">
                <div class="about-header">
                    <h1 class="about-title">How I Built This Site Using AI</h1>
                    <p style="font-size: 1.5rem !important; color: var(--soft-terracotta); margin-top: var(--space-md); margin-bottom: var(--space-lg) !important; font-weight: 600; line-height: 1.4;">What Worked, What Broke, and What I Didn't Expect</p>
                    <div class="about-divider"></div>
                </div>

                <p style="color: var(--deep-espresso); font-weight: 400;">I rebuilt my personal website almost entirely with the help of AI tools. I approached it as an AI tool exploration across the full build process.</p>

                <h2>1. The part AI didn't replace: Research & taste</h2>

                <p>I started with extensive research across personal websites and portfolio sites. <a href="https://www.notion.com/templates/category/personal-website" class="inline-link" target="_blank" rel="noopener noreferrer">Notion personal website templates</a> turned out to be a useful source of inspiration, particularly for individual component patterns. <a href="https://blog.copyfol.io/marketing-portfolio-examples" class="inline-link" target="_blank" rel="noopener noreferrer">Marketing portfolio examples</a> were especially helpful for stylistic direction.</p>

                <p>This phase was almost entirely manual: screenshots, comparisons, notes. The outcome was a clear set of structural and stylistic preferences that informed everything else.</p>

                <h2>2. Translating ideas into wireframes (with ChatGPT)</h2>

                <p>Once I had clear preferences from the research phase, I fed them to ChatGPT and started drilling into the specifics for my site. I used ChatGPT to:</p>
                <ul class="bullet-list">
                    <li>Test various approaches to section hierarchy and content organization</li>
                    <li>Draft text-based wireframes that mapped out page structure</li>
                    <li>Generate rough style mockups to visualize the direction</li>
                </ul>

                <p>Through iteration, I landed on a warm, modern direction: soft neutrals, rounded edges, and a human-tech hybrid feel.</p>

                <p>The output: text-based wireframes that became direct inputs for the site prototyping tool, plus rough visual mockups for my own reference.</p>

                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-lg); margin: var(--space-xl) 0;">
                    <figure style="border-radius: var(--radius-md); overflow: hidden; box-shadow: var(--shadow-soft);">
                        <div style="height: 300px; overflow: hidden;">
                            <img src="/public/images/building-with-ai/chatgpt-wireframe.png" alt="Text-based wireframe generated by ChatGPT" style="width: 100%; height: 100%; object-fit: cover; object-position: top;">
                        </div>
                        <figcaption style="padding: var(--space-md); background: var(--light-beige); font-size: 0.875rem; color: var(--olive-grey); font-style: italic; text-align: center;">
                            Text-based wireframe generated by ChatGPT
                        </figcaption>
                    </figure>

                    <figure style="border-radius: var(--radius-md); overflow: hidden; box-shadow: var(--shadow-soft);">
                        <div style="height: 300px; overflow: hidden;">
                            <img src="/public/images/building-with-ai/chatgpt-visual-mockup.png" alt="Visual mockup generated by ChatGPT showing portfolio layout" style="width: 100%; height: 100%; object-fit: cover; object-position: top;">
                        </div>
                        <figcaption style="padding: var(--space-md); background: var(--light-beige); font-size: 0.875rem; color: var(--olive-grey); font-style: italic; text-align: center;">
                            Visual mockup generated by ChatGPT
                        </figcaption>
                    </figure>
                </div>

                <h2>3. Visual identity: the cartoonification experiment</h2>

                <p>I decided early to use an illustrated portrait instead of a photograph, aiming for a flat, editorial-style aesthetic with a New Yorker-inspired feel.</p>

                <p>I tested Midjourney, DALL·E, Canva, and many tools from <a href="https://www.successtechservices.com/ai-cartoonizers/" class="inline-link" target="_blank" rel="noopener noreferrer">this AI cartoonizer roundup</a>. Despite extensive prompt iteration (often with ChatGPT's help), results were inconsistent.</p>

                <p><strong>Artlist.io</strong> ultimately worked best, producing the closest match to what I had envisioned. I used it for the portrait and case study thumbnails to keep visual language consistent.</p>

                <p>One limitation: Artlist (like most AI image tools) doesn't produce transparent PNGs, requiring post-processing in Photoshop.</p>

                <figure style="margin: var(--space-xl) 0;">
                    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: var(--space-sm); margin-bottom: 0;">
                        <div style="width: 100%; height: 180px; overflow: hidden; border-radius: var(--radius-md); box-shadow: var(--shadow-soft);">
                            <img src="/public/images/building-with-ai/cartoonification-attempts1.jpg" alt="Cartoonification attempt 1" style="width: 100%; height: 100%; object-fit: cover; object-position: center;">
                        </div>
                        <img src="/public/images/building-with-ai/cartoonification-attempts2.png" alt="Cartoonification attempt 2" style="width: 100%; height: auto; border-radius: var(--radius-md); box-shadow: var(--shadow-soft);">
                        <img src="/public/images/building-with-ai/cartoonification-attempts3.png" alt="Cartoonification attempt 3" style="width: 100%; height: auto; border-radius: var(--radius-md); box-shadow: var(--shadow-soft);">
                        <img src="/public/images/building-with-ai/cartoonification-attempts4.png" alt="Cartoonification attempt 4" style="width: 100%; height: auto; border-radius: var(--radius-md); box-shadow: var(--shadow-soft);">
                    </div>
                    <figcaption style="padding: var(--space-md); background: var(--light-beige); font-size: 0.875rem; color: var(--olive-grey); font-style: italic; text-align: center;">
                        Cartoonification attempts, across different tools, that were...not quite right 😅
                    </figcaption>
                </figure>

                <figure style="margin: var(--space-xl) 0; border-radius: var(--radius-md); overflow: hidden; box-shadow: var(--shadow-soft);">
                    <img src="/public/images/building-with-ai/artlist-final-illustration.png" alt="Cartoonification generated by Artlist.io" style="width: 100%; display: block;">
                    <figcaption style="padding: var(--space-md); background: var(--light-beige); font-size: 0.875rem; color: var(--olive-grey); font-style: italic; text-align: center;">
                        Cartoonification generated by Artlist.io
                    </figcaption>
                </figure>

                <h2>4. Site prototyping with AI tools (and when things broke)</h2>

                <p>For prototyping, I used <strong>Magic Patterns</strong>, one of several AI prototyping tools I'd explored during <a href="https://www.reforge.com/courses/ai-productivity" class="inline-link" target="_blank" rel="noopener noreferrer">Reforge's AI Productivity course</a> (alongside Lovable, Bolt, v0).</p>

                <p>Magic Patterns' strength is exploration, especially its Inspiration mode, which generates multiple design variations from the same inputs.</p>

                <p>I fed it the wireframes and visual assets, then iterated extensively. The project reached around 80% complete.</p>

                <p>Then <strong>on December 24th, Magic Patterns rolled out an update</strong>. Previously working prompts stopped producing usable results. I contacted support, got a rollback and extra credits, but issues persisted for days.</p>

                <figure style="margin: var(--space-xl) 0; border-radius: var(--radius-md); overflow: hidden; box-shadow: var(--shadow-soft);">
                    <img src="/public/images/building-with-ai/magic-patterns-inspiration.png" alt="Magic Patterns Inspiration mode interface showing multiple design variations" style="width: 100%; display: block;">
                    <figcaption style="padding: var(--space-md); background: var(--light-beige); font-size: 0.875rem; color: var(--olive-grey); font-style: italic; text-align: center;">
                        Magic Patterns Inspiration mode showing multiple design directions
                    </figcaption>
                </figure>

                <h2>5. Recovery, tool-switching, and site finalization</h2>

                <p>After multiple support exchanges, Magic Patterns eventually worked again. But at the time, thinking things might be broken for good, I moved the project to <strong>Claude Code</strong>, converting from React to PHP (based on advice from someone more technical).</p>

                <p>I still used Magic Patterns for some design decisions, but completed implementation and final refinements in Claude.</p>

                <p><strong>Key lesson:</strong> AI-powered tools, especially LLM-based ones, are probabilistic systems. Their behavior can change unexpectedly due to underlying model updates, which then require adjustments to the prompt engineering layer and tool orchestration. I've written about the distinction between probabilistic and deterministic technology in <a href="https://www.linkedin.com/pulse/looks-like-chatgpt-learned-count-itdidnt-anna-barto-eohmf/" class="inline-link" target="_blank" rel="noopener noreferrer">"It Looks Like ChatGPT Learned to Count. It Didn't."</a></p>

                <p>This project made those dynamics very tangible.</p>

                <h2>6. Final reflection</h2>

                <p>Building this site with AI clarified three things:</p>

                <p><strong>The tools are now powerful enough to enable work that would previously have required much deeper technical expertise or a few different contributors.</strong></p>

                <p><strong>The same power that makes these tools so useful is also a weakness: their probabilistic nature can lead to unpredictable behavior and things breaking unexpectedly.</strong></p>

                <p><strong>They do not remove the need for research, experimentation, judgment, or iteration.</strong></p>

                <p>This site is the result of navigating all three.</p>
            </div>
        </section>
    </main>

    <?php include __DIR__ . '/../includes/footer.php'; ?>
</body>
</html>
