name: Deploy to Staging

on:
  push:
    tags:
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v4

      - name: Deploy to staging
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          DEPLOY_SSH_KNOWN_HOSTS: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
        run: ./stage.sh
